### ISSUE TITLE
I wrote the right IP address, user and password but it's not working?

### ISSUE THREAD

**Issue by Pieloma** [Greg0109/BoardyServer#1]
So I wrote the right ip address, user and password but it's not working and I had right username and password but can you tell me how do I find it, just to check if I did right steps. :)

**Comment by Greg0109** [comment]
You can find your phones ip going to settings -> WiFi and selecting the WiFi you are connected to. 

The username is root

The password (unless you changed which you should) is alpine (no caps)

**Comment by gerardoEsq** [comment]
Why does my phone only sends, but don’t receive from the pc? 

I copied “Haha” from my phone, and I could paste to my pc, but no pc to phone

**Comment by Greg0109** [comment]
Could you try to ssh from your computer to your phone?
Follow this instructions:
https://www.iphonefaq.org/archives/971438

If you can, then enter the same settings (ip, user and password) into the json file. 

If you can't then either the settings are wrong or you have a bad install of openssh (reinstall openssh)

Remember that you must be connected to the same wifi network

**Comment by gustisyailendra** [comment]
> Why does my phone only sends, but don’t receive from the pc?
> 
> I copied “Haha” from my phone, and I could paste to my pc, but no pc to phone

Same with me, i can't receive a message from the pc. https://imgur.com/FWgUzHU.

**Comment by Greg0109** [comment]
> > Why does my phone only sends, but don’t receive from the pc?
> 
> > 
> 
> > I copied “Haha” from my phone, and I could paste to my pc, but no pc to phone
> 
> 
> 
> Same with me, i can't receive a message from the pc. https://imgur.com/FWgUzHU.

Could you install OpenSSH from bingners repo? Http://apt.bingner.com

**Comment by gustisyailendra** [comment]
> > > Why does my phone only sends, but don’t receive from the pc?
> > 
> > 
> > > 
> > 
> > 
> > > I copied “Haha” from my phone, and I could paste to my pc, but no pc to phone
> > 
> > 
> > Same with me, i can't receive a message from the pc. https://imgur.com/FWgUzHU.
> 
> Could you install OpenSSH from bingners repo? https://apt.bingner.com

I can't find "OpenSSH". Btw, why do i need bingners repo? yet my phone jailbreaked using odyssey.
https://i.imgur.com/AW8mFmo.jpg

**Comment by Greg0109** [comment]
> > > > Why does my phone only sends, but don’t receive from the pc?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I copied “Haha” from my phone, and I could paste to my pc, but no pc to phone
> 
> > > 
> 
> > > 
> 
> > > Same with me, i can't receive a message from the pc. https://imgur.com/FWgUzHU.
> 
> > 
> 
> > Could you install OpenSSH from bingners repo? https://apt.bingner.com
> 
> 
> 
> I can't find "OpenSSH". Btw, why do i need bingners repo? yet my phone jailbreaked using odyssey.
> 
> https://i.imgur.com/AW8mFmo.jpg

It's just that it's the one I know it works. Could you try to reinstall openssh from the one you have (Hayden) and then respring?

**Comment by gustisyailendra** [comment]
> > > > > Why does my phone only sends, but don’t receive from the pc?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > I copied “Haha” from my phone, and I could paste to my pc, but no pc to phone
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Same with me, i can't receive a message from the pc. https://imgur.com/FWgUzHU.
> > 
> > 
> > > 
> > 
> > 
> > > Could you install OpenSSH from bingners repo? https://apt.bingner.com
> > 
> > 
> > I can't find "OpenSSH". Btw, why do i need bingners repo? yet my phone jailbreaked using odyssey.
> > https://i.imgur.com/AW8mFmo.jpg
> 
> It's just that it's the one I know it works. Could you try to reinstall openssh from the one you have (Hayden) and then respring?

Just reinstalled and resprang, the problem still exist.

**Comment by ChristianYisus** [comment]
> > Why does my phone only sends, but don’t receive from the pc?
> > I copied “Haha” from my phone, and I could paste to my pc, but no pc to phone
> 
> Same with me, i can't receive a message from the pc. https://imgur.com/FWgUzHU.

Same with me ):

**Comment by Greg0109** [comment]
> > > > > > Why does my phone only sends, but don’t receive from the pc?
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > I copied “Haha” from my phone, and I could paste to my pc, but no pc to phone
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > Same with me, i can't receive a message from the pc. https://imgur.com/FWgUzHU.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > Could you install OpenSSH from bingners repo? https://apt.bingner.com
> > > 
> > > 
> > > I can't find "OpenSSH". Btw, why do i need bingners repo? yet my phone jailbreaked using odyssey.
> > > https://i.imgur.com/AW8mFmo.jpg
> > 
> > 
> > It's just that it's the one I know it works. Could you try to reinstall openssh from the one you have (Hayden) and then respring?
> 
> Just reinstalled and resprang, the problem still exist.

Try using the one from Bingners repo then

**Comment by Greg0109** [comment]
> > > Why does my phone only sends, but don’t receive from the pc?
> > > I copied “Haha” from my phone, and I could paste to my pc, but no pc to phone
> > 
> > 
> > Same with me, i can't receive a message from the pc. https://imgur.com/FWgUzHU.
> 
> Same with me ):

Make sure you entered the correct iphone settings on the ServerConfig.json file. You can try to ssh from your PC to your iphone to confirm said settings.

**Comment by gustisyailendra** [comment]
> > > > > > > Why does my phone only sends, but don’t receive from the pc?
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > > I copied “Haha” from my phone, and I could paste to my pc, but no pc to phone
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > Same with me, i can't receive a message from the pc. https://imgur.com/FWgUzHU.
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > Could you install OpenSSH from bingners repo? https://apt.bingner.com
> > > > 
> > > > 
> > > > I can't find "OpenSSH". Btw, why do i need bingners repo? yet my phone jailbreaked using odyssey.
> > > > https://i.imgur.com/AW8mFmo.jpg
> > > 
> > > 
> > > It's just that it's the one I know it works. Could you try to reinstall openssh from the one you have (Hayden) and then respring?
> > 
> > 
> > Just reinstalled and resprang, the problem still exist.
> 
> Try using the one from Bingners repo then

So it means your tweak doesn't work on Odyssey? Searched it but can't find "openssh". Can i request for refund?

**Comment by Greg0109** [comment]
> > > > > > > > Why does my phone only sends, but don’t receive from the pc?
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > > I copied “Haha” from my phone, and I could paste to my pc, but no pc to phone
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > >
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > > Same with me, i can't receive a message from the pc. https://imgur.com/FWgUzHU.
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > 
> 
> > > > > 
> 
> > > > > 
> 
> > > > > > Could you install OpenSSH from bingners repo? https://apt.bingner.com
> 
> > > > > 
> 
> > > > > 
> 
> > > > > I can't find "OpenSSH". Btw, why do i need bingners repo? yet my phone jailbreaked using odyssey.
> 
> > > > > https://i.imgur.com/AW8mFmo.jpg
> 
> > > > 
> 
> > > > 
> 
> > > > It's just that it's the one I know it works. Could you try to reinstall openssh from the one you have (Hayden) and then respring?
> 
> > > 
> 
> > > 
> 
> > > Just reinstalled and resprang, the problem still exist.
> 
> > 
> 
> > Try using the one from Bingners repo then
> 
> 
> 
> So it means your tweak doesn't work on Odyssey? Searched it but can't find "openssh". Can i request for refund?

Before that, please check what port does your iPhone have for ssh. Boardy uses the default one (22) maybe you changed it or odyssey has a different one. 

You are the only odyssey user who is having troubles

**Comment by MrPigglet** [comment]
Using Odysseyra1n, I can copy text from iPhone to PC but not from PC to iPhone.

**Comment by Greg0109** [comment]
> Using Odysseyra1n, I can copy text from iPhone to PC but not from PC to iPhone.

Refer to the FAQ section of the GitHub please

**Comment by MrPigglet** [comment]
> > Using Odysseyra1n, I can copy text from iPhone to PC but not from PC to iPhone.
> 
> Refer to the FAQ section of the GitHub please

I can confirm that my phone has the SSH port 22 according to sshd_config. My Config file should be perfectly set up but I can still not copy text from PC to iPhone

**Comment by Pieloma** [comment]
> Could you try to ssh from your computer to your phone?
> Follow this instructions:
> https://www.iphonefaq.org/archives/971438
> 
> If you can, then enter the same settings (ip, user and password) you just used to ssh into the json file. 
> 
> If you can't then either the settings are wrong or you have a bad install of openssh (reinstall openssh)
> 
> Remember that you must be connected to the same wifi network 

I tried to ssh in my phone but I couldn't? I had the right password again and right username.

**Comment by Greg0109** [comment]
> > > Using Odysseyra1n, I can copy text from iPhone to PC but not from PC to iPhone.
> 
> > 
> 
> > Refer to the FAQ section of the GitHub please
> 
> 
> 
> I can confirm that my phone has the SSH port 22 according to sshd_config. My Config file should be perfectly set up but I can still not copy text from PC to iPhone
> 
> 
> 
> Edit: Found out I could not SSH into my phone on port 22. I can SSH into it with port 2222, so if you add the functionality for Boardy to use custom ports my issue would probably be fixed.

If you remove the # from the line of Port 22 it will enable the default port (a reboot might be needed) also check that there's no other line that specifies the port on the file

**Comment by Greg0109** [comment]
> > Could you try to ssh from your computer to your phone?
> > Follow this instructions:
> > https://www.iphonefaq.org/archives/971438
> > 
> > If you can, then enter the same settings (ip, user and password) you just used to ssh into the json file. 
> > 
> > If you can't then either the settings are wrong or you have a bad install of openssh (reinstall openssh)
> > 
> > Remember that you must be connected to the same wifi network 
> 
> I tried to ssh in my phone but I couldn't? I had the right password again and right username.

It's the port. Most likely is on 2222. Follow the instructions on the github to see the port and remove the # on that line. Make sure it doesn't repeat the port line anywhere else on that file (a reboot might be needed)

**Comment by gustisyailendra** [comment]
> > > > > > > > > Why does my phone only sends, but don’t receive from the pc?
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > > I copied “Haha” from my phone, and I could paste to my pc, but no pc to phone
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > > Same with me, i can't receive a message from the pc. https://imgur.com/FWgUzHU.
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > > Could you install OpenSSH from bingners repo? https://apt.bingner.com
> > 
> > 
> > > > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > > > > I can't find "OpenSSH". Btw, why do i need bingners repo? yet my phone jailbreaked using odyssey.
> > 
> > 
> > > > > > https://i.imgur.com/AW8mFmo.jpg
> > 
> > 
> > > > >
> > 
> > 
> > > > >
> > 
> > 
> > > > > It's just that it's the one I know it works. Could you try to reinstall openssh from the one you have (Hayden) and then respring?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Just reinstalled and resprang, the problem still exist.
> > 
> > 
> > > 
> > 
> > 
> > > Try using the one from Bingners repo then
> > 
> > 
> > So it means your tweak doesn't work on Odyssey? Searched it but can't find "openssh". Can i request for refund?
> 
> Before that, please check what port does your iPhone have for ssh. Boardy uses the default one (22) maybe you changed it or odyssey has a different one.
> 
> You can find more info here: https://github.com/Greg0109/Boardyserver#it-sends-the-text-to-my-pc-but-not-my-iphone-why-is-that
> 
> You are the only odyssey user who is having troubles.

That's weird tho, switched to u0 and it works. The next problem is i can't copy an image from PC to iPhone but the text can be copied (new version).

**Comment by Greg0109** [comment]
> > > > > > > > > > Why does my phone only sends, but don’t receive from the pc?
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > > > I copied “Haha” from my phone, and I could paste to my pc, but no pc to phone
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > > Same with me, i can't receive a message from the pc. https://imgur.com/FWgUzHU.
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > > Could you install OpenSSH from bingners repo? https://apt.bingner.com
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > > I can't find "OpenSSH". Btw, why do i need bingners repo? yet my phone jailbreaked using odyssey.
> 
> > > 
> 
> > > 
> 
> > > > > > > https://i.imgur.com/AW8mFmo.jpg
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > >
> 
> > > 
> 
> > > 
> 
> > > > > > It's just that it's the one I know it works. Could you try to reinstall openssh from the one you have (Hayden) and then respring?
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > >
> 
> > > 
> 
> > > 
> 
> > > > > Just reinstalled and resprang, the problem still exist.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Try using the one from Bingners repo then
> 
> > > 
> 
> > > 
> 
> > > So it means your tweak doesn't work on Odyssey? Searched it but can't find "openssh". Can i request for refund?
> 
> > 
> 
> > Before that, please check what port does your iPhone have for ssh. Boardy uses the default one (22) maybe you changed it or odyssey has a different one.
> 
> > 
> 
> > You can find more info here: https://github.com/Greg0109/Boardyserver#it-sends-the-text-to-my-pc-but-not-my-iphone-why-is-that
> 
> > 
> 
> > You are the only odyssey user who is having troubles.
> 
> 
> 
> That's weird tho, switched to u0 and it works. The next problem is i can't copy an image from PC to iPhone but the text can be copied (new version).

Images cannot be copied from a file, they must be copied like a image (from the internet or screenshot or opening the image and copying). Big images (>14 mg) might fail to copy

**Comment by gustisyailendra** [comment]
> > > > > > > > > > > Why does my phone only sends, but don’t receive from the pc?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > > > I copied “Haha” from my phone, and I could paste to my pc, but no pc to phone
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > > Same with me, i can't receive a message from the pc. https://imgur.com/FWgUzHU.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > > Could you install OpenSSH from bingners repo? https://apt.bingner.com
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > I can't find "OpenSSH". Btw, why do i need bingners repo? yet my phone jailbreaked using odyssey.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > > https://i.imgur.com/AW8mFmo.jpg
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > > It's just that it's the one I know it works. Could you try to reinstall openssh from the one you have (Hayden) and then respring?
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > > Just reinstalled and resprang, the problem still exist.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > >
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > Try using the one from Bingners repo then
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > So it means your tweak doesn't work on Odyssey? Searched it but can't find "openssh". Can i request for refund?
> > 
> > 
> > > 
> > 
> > 
> > > Before that, please check what port does your iPhone have for ssh. Boardy uses the default one (22) maybe you changed it or odyssey has a different one.
> > 
> > 
> > > 
> > 
> > 
> > > You can find more info here: https://github.com/Greg0109/Boardyserver#it-sends-the-text-to-my-pc-but-not-my-iphone-why-is-that
> > 
> > 
> > > 
> > 
> > 
> > > You are the only odyssey user who is having troubles.
> > 
> > 
> > That's weird tho, switched to u0 and it works. The next problem is i can't copy an image from PC to iPhone but the text can be copied (new version).
> 
> Images cannot be copied from a file, they must be copied like a image (from the internet or screenshot or opening the image and copying). Big images (>14 mb) might fail to copy

Tried it already ):

**Comment by Pieloma** [comment]
I tried installing boardy server but it's keep getting removed, I even turned off my antivirus.

**Comment by Greg0109** [comment]
> I tried installing boardy server but it's keep getting removed, I even turned off my antivirus.

Turn off windows defender
