### ISSUE TITLE
Not copying from IPhone to PC

### ISSUE THREAD

**Issue by TheIronboy** [Greg0109/BoardyServer#14]
i already tried what is written on the readme.md, the ssh connection works and it isn't copying.

**Comment by Greg0109** [comment]
Make sure the pc ip is correct and on the tweak settings. Make sure the iPhone ip is correct and on the settings.json. The settings.json file must be on the same folder as the executable and named exactly as "settings.json" caps sensitive

**Comment by TheIronboy** [comment]
i found the problem, the tweak is not working with the windows 10 hotspot.
can it be fixed?

**Comment by Greg0109** [comment]
Try using hostnames instead of ip. How to find hostnames can be found on the FAQ

**Comment by TheIronboy** [comment]
already tried with and without the .local at the end.
it works only from the pc to iphone.

**Comment by TheIronboy** [comment]
fixed by allowing firewall connection.
