### ISSUE TITLE
Windows defender scans BoardyServer.exe as trojan

### ISSUE THREAD

**Issue by JellyPeixe** [Greg0109/BoardyServer#2]
Since its release, I've been using Boardy as a handy tweak to copy my clipboard through devices but one day as I turned on my computer the server was gone. So I downloaded it again but windows defender thinks its a "Program:Win32/Waxapew.C!ml". I mean, I trust the developer but I wonder why is that?

**Comment by Greg0109** [comment]
> Since its release, I've been using Boardy as a handy tweak to copy my clipboard through devices but one day as I turned on my computer the server was gone. So I downloaded it again but windows defender thinks its a "Program:Win32/Waxapew.C!ml". I mean, I trust the developer but I wonder why is that?

Since the server enables a form of local networking (connectivity between devices) but doesn't have any official certificate (that proves it isn't malware), firewalls and antivirus might see it as such. I will get certificates for the servers when I have some free time. Thanks for your feedback
