### ISSUE TITLE
Specify port

### ISSUE THREAD

**Issue by saboooor** [Greg0109/BoardyServer#3]
SSH doesn't seem to work with boardyserver, but when i ssh into my phone with -p 2222, it works
Is there a way to change the port to 2222 instead of the one used in boardyserver?

**Comment by Greg0109** [comment]
> SSH doesn't seem to work with boardyserver, but when i ssh into my phone with -p 2222, it works
> 
> Is there a way to change the port to 2222 instead of the one used in boardyserver?

At the moment BoardyServer uses the default ssh port (22, you seem to have changed the ssh port on your iPhone) and cannot be changed. I will add a setting for that once I have some free time. 

For the moment you can go back to /etc/ssh/sshd_config on your iPhone and specify port 22 as the port.
