### ISSUE TITLE
Unable to run BoardyServer on Linux

### ISSUE THREAD

**Issue by bja-au** [Greg0109/BoardyServer#4]
G'day,
I run Solus Linux on my Macmini and have installed BoardyServer ok, amended the .json file and confirmed settings ok using ssh.
Unfortunately whenever I run BoardyServer I get the following error ...
[575477] Error loading Python lib '/tmp/_MEIMr7es1/libpython3.8.so.1.0': dlopen: /usr/lib/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/_MEIMr7es1/libpython3.8.so.1.0)
... Any ideas please?
Thanks
BJA

**Comment by Greg0109** [comment]
> G'day,
> 
> I run Solus Linux on my Macmini and have installed BoardyServer ok, amended the .json file and confirmed settings ok using ssh.
> 
> Unfortunately whenever I run BoardyServer I get the following error ...
> 
> [575477] Error loading Python lib '/tmp/_MEIMr7es1/libpython3.8.so.1.0': dlopen: /usr/lib/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/_MEIMr7es1/libpython3.8.so.1.0)
> 
> ... Any ideas please?
> 
> Thanks
> 
> BJA

Download python3 and the following python modules:
- clipboard
- pillow
- flask
- paramiko

**Comment by bja-au** [comment]
Have installed all those however get same error :(

**Comment by Greg0109** [comment]
> Have installed all those however get same error :(

https://ubuntu.pkgs.org/20.04/ubuntu-main-amd64/libpython3.8_3.8.2-1ubuntu1_amd64.deb.html

**Comment by bja-au** [comment]
Ah bugger - I am running Solus linux 4.1 Fortitude and have ...
/usr/lib64/libpython3.7m.so.1.0
... installed. Looks like I need to wait for an update :(

**Comment by Greg0109** [comment]
> Ah bugger - I am running Solus linux 4.1 Fortitude and have ...
> 
> /usr/lib64/libpython3.7m.so.1.0
> 
> ... installed. Looks like I need to wait for an update :(

Perhaps you could try to install it manually

**Comment by bja-au** [comment]
yeah thought of that however lots of Solus main utils are Python based and I don't want to stuff my system so I will wait until they update the lib to 3.8
Thanks for your help

**Comment by bja-au** [comment]
Sorry to keep harping on but just thought is there a way you could include the lib in the application???
