### ISSUE TITLE
Possible to add multiple IP?

### ISSUE THREAD

**Issue by MrPigglet** [Greg0109/BoardyServer#5]
My phone switches between our 2.4GHz and 5GHz band. It has different IPs. Is there any way to make it work seamlessly over both?

**Comment by Greg0109** [comment]
> My phone switches between our 2.4GHz and 5GHz band. It has different IPs. Is there any way to make it work seamlessly over both?

Use the hostname instead of the ip

**Comment by MrPigglet** [comment]
> > My phone switches between our 2.4GHz and 5GHz band. It has different IPs. Is there any way to make it work seamlessly over both?
> 
> Use the hostname instead of the ip

How can I find the hostname of my iPhone?

**Comment by Greg0109** [comment]
> > > My phone switches between our 2.4GHz and 5GHz band. It has different IPs. Is there any way to make it work seamlessly over both?
> 
> > 
> 
> > Use the hostname instead of the ip
> 
> 
> 
> How can I find the hostname of my iPhone?

![image](https://user-images.githubusercontent.com/9938142/101233233-8f897f00-36b7-11eb-88a2-5771aab1baa8.png)

Where you see iPhone-de-Greg that's my hostname. You would put the hostname with .local at the end
