### ISSUE TITLE
Unable to change port from port 22

### ISSUE THREAD

**Issue by vanimox** [Greg0109/BoardyServer#8]
I just purchased BoardyServer which appears to have incredible potential. That being said, I have my port changed from port 22 to a different port for multiple reasons and changing the port back to 22 would interfere with other settings that I have setup on my device. I know you stated in the documentation that you would be adding support for changing ports in the future, but in the meantime, could you provide instruction on how I might be able to manually change the port so I can actually use BoardyServer?

Thank you for your time!

**Comment by Greg0109** [comment]
> I just purchased BoardyServer which appears to have incredible potential. That being said, I have my port changed from port 22 to a different port for multiple reasons and changing the port back to 22 would interfere with other settings that I have setup on my device. I know you stated in the documentation that you would be adding support for changing ports in the future, but in the meantime, could you provide instruction on how I might be able to manually change the port so I can actually use BoardyServer?
> 
> 
> 
> Thank you for your time!

Hi, at this moment there's no way to manually change the port, since the executable is compiled an all, I'm sorry but you will have to wait for the update
