### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Xenfo** [Greg0109/BoardyServer#9]
May I know why the virus total is like this?
https://www.virustotal.com/gui/file/79c0a49591696757a071ba8cf46333459c8fac18967434e4c488954f00dcdb36/detection

**Comment by Greg0109** [comment]
> May I know why the virus total is like this?
> 
> https://www.virustotal.com/gui/file/79c0a49591696757a071ba8cf46333459c8fac18967434e4c488954f00dcdb36/detection

https://github.com/greg0109/boardyserver#the-server-gets-flagged-as-a-trojanvirus-is-it-safe-the-server-was-deleted-and-i-had-to-download-it-again-windows-firewallantivirus

**Comment by Xenfo** [comment]
Alright just making sure. Mcafee really doesn't like it even when I add it to the whitelist.
